### ISSUE TITLE
crash when minimizing

### ISSUE THREAD

**Issue by jeltedeproft** [crykn/libgdx-screenmanager#18]
I get a crash when I minimize the game, not when I resize it, with the following stack trace

```
Exception in thread "main" java.lang.IllegalStateException: Frame buffer couldn't be constructed: incomplete attachment
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:256)
	at de.damios.guacamole.gdx.graphics.NestableFrameBuffer.build(NestableFrameBuffer.java:162)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:75)
	at de.damios.guacamole.gdx.graphics.NestableFrameBuffer.<init>(NestableFrameBuffer.java:58)
	at de.damios.guacamole.gdx.graphics.NestableFrameBuffer.<init>(NestableFrameBuffer.java:79)
	at de.eskalon.commons.screen.ScreenManager.initBuffers(ScreenManager.java:150)
	at de.eskalon.commons.screen.ScreenManager.resize(ScreenManager.java:399)
	at com.jelte.myGames.Ponko.resize(Ponko.java:76)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Graphics$1$1.run(Lwjgl3Graphics.java:88)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:208)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.jelte.myGames.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:14)
	at com.jelte.myGames.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:10)
```

gdxVersion=1.11.0
screenManagerVersion=0.6.8

**Comment by crykn** [comment]
Hey, could you check what width and height values `Ponko#resize(int, int)` gives to `ScreenManager#resize(int, int)`?

**Comment by jeltedeproft** [comment]
That would be

width = 0
height = 0

**Comment by crykn** [comment]
That explains the issue: framebuffers can't be created with a size of 0x0. Does `Ponko` extend `ManagedGame`? If so, calling `super.resize(width, height);` in `Ponko#resize(int, int)` would filter these values out. If not, just add something like [this](https://github.com/crykn/libgdx-screenmanager/blob/7e38792863585bb6e0fa62512a87ebbcd18ab652/src/main/java/de/eskalon/commons/core/ManagedGame.java#L90-L95) to your resize method.

**Comment by jeltedeproft** [comment]
Thank you, Ponko did extend ManagedGame, calling super.resize() als odidnt fix it, but just adding the 0,0 check fixed it.

**Comment by crykn** [comment]
> calling super.resize() also didnt fix it

Hm, that is weird. Are you calling `ScreenManager#resize(int, int);` yourself? That would explain why the filtering done in `ManagedGame#resize(int, int)` has no effect.

**Comment by jeltedeproft** [comment]
ah yeah I do actually
